exec-once = ~/.local/bin/hyprland-per-window-layout
exec-once = xmodmap -e "keycode 108 = F3"

# Services
exec-once = systemctl --user enable --now hypridle.service
exec-once = systemctl --user enable --now hyprpaper.service
exec-once = systemctl --user enable --now hyprsunset.service
exec-once = systemctl --user enable --now waybar.service
exec-once = systemctl --user enable --now vicinae.service

# Cursor fix test
exec-once = hyprctl setcursor macOS 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'macOS'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

# Applications
exec-once = [workspace 2 silent] ~/.config/hypr/scripts/entry-launch.sh cursor
exec-once = [workspace 3 silent] ~/.config/hypr/scripts/entry-launch.sh app.zen_browser.zen
exec-once = [workspace 4 silent] ~/.config/hypr/scripts/entry-launch.sh org.telegram.desktop