exec-once = ~/.local/bin/hyprland-per-window-layout
exec-once = xmodmap -e "keycode 108 = F3"
# exec-once = hyprctl setcursor GoogleDot-Black 24
exec-once = systemctl --user enable --now hypridle.service
exec-once = systemctl --user enable --now hyprpaper.service
exec-once = systemctl --user enable --now hyprsunset.service
exec-once = systemctl --user enable --now waybar.service
exec-once = systemctl --user enable --now vicinae.service

# Applications
exec-once = [workspace 2 silent] ~/.config/hypr/scripts/entry-launch.sh cursor
exec-once = [workspace 2 silent] ~/.config/hypr/scripts/entry-launch.sh app.zen_browser.zen
exec-once = [workspace 3 silent] ~/.config/hypr/scripts/entry-launch.sh org.telegram.desktop