# Fast apps
bind = SUPER, 1, exec, ~/.config/hypr/scripts/entry-launch.sh kitty
bind = SUPER, 2, exec, ~/.config/hypr/scripts/entry-launch.sh org.gnome.Nautilus
bind = SUPER, 3, exec, XDG_CURRENT_DESKTOP=GNOME ~/.config/hypr/scripts/entry-launch.sh org.gnome.Settings
bind = SUPER, 4, exec, ~/.config/hypr/scripts/entry-launch.sh org.gnome.Software
bind = SUPER, 5, exec, [workspace 1] ~/.config/hypr/scripts/entry-launch.sh youtube-music
bind = SUPER, 6, exec, [workspace 4] ~/.config/hypr/scripts/entry-launch.sh org.signal.Signal
bind = SUPER, 7, exec, [workspace 4] ~/.config/hypr/scripts/entry-launch.sh org.telegram.desktop
bind = SUPER, 8, exec, [workspace 3] ~/.config/hypr/scripts/entry-launch.sh app.zen_browser.zen
bind = SUPER, 9, exec, ~/.config/hypr/scripts/entry-launch.sh cursor
bind = SUPER, 0, exec, ~/.config/hypr/scripts/entry-launch.sh md.obsidian.Obsidian

bind = SUPER CTRL, 1, exec, ~/.config/hypr/scripts/entry-launch.sh --new kitty
bind = SUPER CTRL, 2, exec, ~/.config/hypr/scripts/entry-launch.sh --new org.gnome.Nautilus
bind = SUPER CTRL, 3, exec, XDG_CURRENT_DESKTOP=GNOME ~/.config/hypr/scripts/entry-launch.sh --new org.gnome.Settings
bind = SUPER CTRL, 4, exec, ~/.config/hypr/scripts/entry-launch.sh --new org.gnome.Software
bind = SUPER CTRL, 5, exec, ~/.config/hypr/scripts/entry-launch.sh --new youtube-music
bind = SUPER CTRL, 6, exec, ~/.config/hypr/scripts/entry-launch.sh --new org.signal.Signal
bind = SUPER CTRL, 7, exec, ~/.config/hypr/scripts/entry-launch.sh --new org.telegram.desktop
bind = SUPER CTRL, 8, exec, ~/.config/hypr/scripts/entry-launch.sh --new app.zen_browser.zen
bind = SUPER CTRL, 9, exec, ~/.config/hypr/scripts/entry-launch.sh --new cursor
bind = SUPER CTRL, 0, exec, ~/.config/hypr/scripts/entry-launch.sh --new md.obsidian.Obsidian