# See https://wiki.hypr.land/Configuring/Monitors/

# Default
monitor=,preferred,auto,1.0,bitdepth,10
monitor=eDP-1,1920x1080@144,-1920x0,1.0,bitdepth,10
monitor=HDMI-A-1,2560x1440@75,0x0,1.0,bitdepth,10

# Overwrite
source = ~/.config/hypr/modules/monitors/overwrite.conf