text = 0xFFDADADA
bright_text = 0xFFFFDEDE
background = 0xFF222226
base = 0xFF2E2E32
alternate_base = 0xFF272727
accent = 0xFF6F8396
accent_secondary = 0xFF96bddb
h1_size = 64
h2_size = 20
h3_size = 18
font_size = 17
small_font_size = 12
font_family = SF Pro Medium
font_family_monospace = Liga SFMono Nerd Font Medium
rounding_large = 16
rounding_small = 8
icon_theme =