$font = SF Pro Bold

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(6f8396ee) rgba(6f8396ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 16

    font_family = $font
    placeholder_text = 
    fail_text = ERROR


    dots_size = 0.33

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 120
    font_family = $font

    position = 0, 120
    halign = center
    valign = center
}

# DATE
# label {
#     monitor =
#     text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
#     font_size = 25
#     font_family = $font

#     position = -30, -150
#     halign = right
#     valign = top
# }

# label {
#     monitor =
#     text = $LAYOUT[en,ru,ua]
#     font_size = 24
#     onclick =

#     position = 0%, -90
#     halign = center
#     valign = center
# }