splash = false

wallpaper {
    monitor = 
    path = ~/.local/share/backgrounds/2025-08-04-13-12-16-148305-gornyj_hrebet-nagore-gornyj_relef-atmosfera-plato-7680x4320.jpg
    timeout = 150
    fit_mode = cover
}