splash = false

wallpaper {
    monitor = 
    path = ~/.local/share/backgrounds/2025-08-04-13-12-16-143309-podzemnye_vody-oblako-atmosfera-nebo-tumannost-7680x4320.jpg
    timeout = 150
    fit_mode = cover
}