general {
    immediate_render = true
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 500
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = 
    path = /home/eduard/.local/share/backgrounds/red-room.png
    blur_passes = 3
}

input-field {
    monitor =
    size = 10%, 3%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.15)

    outer_color = rgba(6f8396ee) rgba(6f8396ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(214, 214, 214)
    fade_on_empty = false
    rounding = 50

    font_family = SF Compact Rounded Bold
    placeholder_text = 
    fail_text = ERROR

    dots_size = 0.5

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 120
    font_family = SF Pro Rounded Bold

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 24
    font_family = SF Compact Rounded Bold

    position = -30, -180
    halign = right
    valign = top
}

# Percentage
label {
    monitor =
    text = cmd[update:30000] /bin/bash -lc 'val=$(cat /sys/class/power_supply/BAT*/capacity | tr -d "\n"); echo -n "     ${val}%";'
    font_size = 24
    font_family = SF Compact Rounded Bold

    position = -30, -220
    halign = right
    valign = top
}

# Language
# label {
#     monitor =
#     text = $LAYOUT[en,ru,ua]
#     font_size = 24
#     onclick =

#     position = 0%, -90
#     halign = center
#     valign = center
# }